### PR TITLE
Clean up the list of locales for engagement

### PR DESCRIPTION
**Pull request by flodolo**
Open question for nb-NO:
- There is one file, but it's not translated
- It was never enabled in Pontoon

Should it be kept and added to Pontoon instead?

### CODE REVIEW

**Comment by TheoChevalier** [comment]
I’m confused, did `ja` got disabled from Pontoon yesterday by mistake, or it wasn’t enabled in the first place? At the same time, there is translated content in the `ja` folder…

**Comment by flodolo** [comment]
> I’m confused, did `ja` got disabled from Pontoon yesterday by mistake, or it wasn’t enabled in the first place? At the same time, there is translated content in the `ja` folder…

Yes, Japanese was removed from Pontoon by mistake, I'll add it back. Stage still has all the locales.
https://mozilla-pontoon-staging.herokuapp.com/projects/engagement/

nb-NO was enabled, but they never translated MoFo email. Should we keep it?

**Comment by TheoChevalier** [comment]
> > I’m confused, did `ja` got disabled from Pontoon yesterday by mistake, or it wasn’t enabled in the first place? At the same time, there is translated content in the `ja` folder…
> 
> Yes, Japanese was removed from Pontoon by mistake, I'll add it back. Stage still has all the locales.
> https://mozilla-pontoon-staging.herokuapp.com/projects/engagement/

Ok, thanks!

> 
> nb-NO was enabled, but they never translated MoFo email. Should we keep it?

No, totally fine to drop

**Comment by flodolo** [comment]
> nb-NO was enabled, but they never translated MoFo email. Should we keep it?

Never mind, saw your reply on Slack about this one. Japanese should be restored in the next sync on Pontoon.

**Pull request merged**
