### PR TITLE
Add ESLint for JavaScript, improve scripts

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@pascalchevrel @TheoChevalier 
Thoughts on the idea of using a linter for JavaScript? I kept separate commits to make things easier to follow. Also borrowed most of the ESLint configuration from bedrock.

Langchecker doesn't really have much JS, but it might be useful for larger projects like Transvision.

**Comment by flodolo** [comment]
Tested introducing an error, and it [properly fails](https://travis-ci.org/mozilla-l10n/langchecker/jobs/119480461).

**Comment by flodolo** [comment]
If you want to use ESLint locally, just install it with npm (`npm install -g eslint`). I'm currently using this [plugin](https://atom.io/packages/linter-eslint) for Atom.

**Comment by TheoChevalier** [comment]
We're not heavy JS users, but I'd say that's nice to have, given that we can exclude external libs. :+1:

**Comment by flodolo** [comment]
The command is currently running only on `web/assets/js` in Travis, and it's already excluding `sorttable.js`, so we can definitely ignore libraries.

**Pull request merged**
