### PR TITLE
Add firefox/browsers.lang & firefox/products.lang

### PR DESCRIPTION
**Pull request by amychurchwell**
Refs: 
firefox/browsers - https://github.com/mozilla-l10n/www.mozilla.org/pull/366
firefox/products - https://github.com/mozilla-l10n/www.mozilla.org/pull/367

### CODE REVIEW

**Comment by peiying2** [comment]
What are the deadlines for these pages? I need to post them in Pontoon for the communities.

**Comment by amychurchwell** [comment]
@peiying2 oops, I was under the impression that deadlines were optional. We could put March 31. I will update this PR.

**Comment by peiying2** [comment]
> @peiying2 oops, I was under the impression that deadlines were optional. We could put March 31. I will update this PR.

Though not needed in the file, if there is a deadline, I need to add the info in Pontoon.

**Comment by amychurchwell** [comment]
@peiying2 we can say March 31. It is not tied to a release or an event. Is this file okay as-is? Or should I remove deadline information?

**Comment by peiying2** [comment]
> @peiying2 we can say March 31. It is not tied to a release or an event. Is this file okay as-is? Or should I remove deadline information?

No need to make anymore changes.

**Pull request merged**
