### PR TITLE
Integrate Travis, fix missing 'static' causing the build to fail

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@pascalchevrel I was thinking: would it make sense to have a #l10n-tools channel on IRC and use it for all Travis+Github notifications?

P.S. I tried to copy Transvision IRC section in travis.yml, but it didn't seem to work

**Comment by pascalchevrel** [comment]
The problem with centralizing notifications in a separate channel is that those notifications would become invisible to Transvision contributors, so #l10n-tools sounds good to me for our team needs as long as as project like Transvision which is more open to external contributions is not included.

**Comment by pascalchevrel** [comment]
Also, the IRC part needs settings to be added in the preferences for the repo

**Comment by flodolo** [comment]
I wasn't clear: I don't want to move Transvision's notifications, those belong to #transvision.

I was talking of all the tools we have here in mozilla-l10

**Comment by pascalchevrel** [comment]
then yes, that's probably a good idea

**Comment by pascalchevrel** [comment]
Then yes, all notifications to our internal tools into a separate IRC channel is fine, we can also talk there about the tools intead of the  l10n-drivers channel

**Pull request merged**
