### PR TITLE
Add firefox/all-unified.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/310

### CODE REVIEW

**Comment by alexgibson** [comment]
@peiying2 r?

**Comment by alexgibson** [comment]
@peiying2 can you please merge this PR, I can then extract lang files for the other locales. Thanks!

**Comment by flodolo** [comment]
PRs adding new files should be merged after the PR actually adding the file (or at the same time as), otherwise they'll generate a ton of errors in tools.

You can still add the files by running the script with your branch of langchecker selected locally.

**Comment by alexgibson** [comment]
I learn new arcane knowledge of this system every day.

**Comment by flodolo** [comment]
> I learn new arcane knowledge of this system every day.

For background:
- The moment you add the file to langchecker, the system will search for this file for all languages that are supposed to have it.
- Throw a bunch of warning in the server's log, and make [this page](https://l10n.mozilla-community.org/langchecker/?action=errors) completely unusable ;-)

**Pull request merged**
