### PR TITLE
add locale id to smarton files per bug 1443287

### PR DESCRIPTION
**Pull request by peiying2**

### CODE REVIEW

**Comment by flodolo** [comment]
Do we want this without even asking the Community? Or have you already done that?

**Comment by peiying2** [comment]
No, I have not. This came from marketing team as id is a focused market. I will ping them, or should I wait until I hear back?

**Comment by flodolo** [comment]
> I will ping them, or should I wait until I hear back?

The latter. Marketing needs to understand that pages are not translated magically, either it's the Community or a Vendor, but we can't throw content at them without even asking.

**Comment by peiying2** [comment]
Let me check on them.

**Comment by peiying2** [comment]
ID team just replied. They will cover this one.

**Comment by flodolo** [comment]
OK, let's merge then.

**Pull request merged**
