### PR TITLE
Add whatsnew 70

### PR DESCRIPTION
**Pull request by amychurchwell**
Ref: https://github.com/mozilla-l10n/www.mozilla.org/pull/332

### CODE REVIEW

**Comment by amychurchwell** [comment]
@peiying2 Mozilla staff are going to localize DE and FR, do I need to declare that in langchecker or just coordinate with you?

**Comment by peiying2** [comment]
> @peiying2 Mozilla staff are going to localize DE and FR, do I need to declare that in langchecker or just coordinate with you?

We have communicated to the respective communities on this and more pages before October launch. There is no way to do that from langchecker, :).

**Comment by peiying2** [comment]
The PR looks good. Could you confirm if the date is the due date to Releng for a full list of locales to be included?

**Comment by amychurchwell** [comment]
@peiying2 
I updated the due date based on the schedule I was given of:
- **Go live - Friday October 11th**
- QA (external) - Mon Oct 14
- Firefox 70 Rapid Release - Tues Oct 22

I was told that all other locales other than DE and FR were opt-in.

**Pull request merged**
