### PR TITLE
Add heartbeat/2016/nov2016.lang

### PR DESCRIPTION
**Pull request by peiying2**

### CODE REVIEW

**Comment by flodolo** [comment]
This looks good 👍 

Ready to merge, as soon as we confirm the weird string.

**Comment by peiying2** [comment]
Looks like the string appeared in the Sept version (they must have loved it):
Take your tabs on the road with Firefox for iOS and Android

**Comment by TheoChevalier** [comment]
I assume “Your Firefox Account meets your phone. They fall in love.” is associated to “Make a match”? If yes, we should mention it because literal translations won’t work here

**Comment by peiying2** [comment]
Yes, the button is next to the string.  should we move the two strings next to each other?

**Comment by flodolo** [comment]
Reorganized the strings with new comments, still need to figure out what to do with the free range tabs 🐔

**Comment by TheoChevalier** [comment]
> Yes, the button is next to the string. should we move the two strings next to each other?
We should add a note saying that this particular button is used with this specific string, and not with another one

**Pull request merged**
