### PR TITLE
Add browser-history page

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@peiying2 I asked about priority locales and got this response: https://github.com/mozilla/bedrock/issues/7060#issuecomment-483314070

Let me know what you think I should adjust here if anything. Thanks

**Comment by peiying2** [comment]
@alexgibson depending on the long term interest in the page, you can use these three examples:

1). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L228 - we only make the page available in identified locales.
2). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L297 - we make it available for all locales, but we list the required locales for now. Other communities can ask for their locales at a later time. I will take care of these requests.
3). https://github.com/mozilla-l10n/langchecker/blob/master/app/config/sources.inc.php#L209 - for all Firefox locales, this is optional. Then you specify the supported locales in the first go around (now). Other communities can ask for it later and I will take care of those.

**Comment by alexgibson** [comment]
@peiying2 I went for option 2, thanks. If this looks good, please merge and I'll extract the strings for all locales in https://github.com/mozilla-l10n/www.mozilla.org/pull/290

**Comment by peiying2** [comment]
https://github.com/mozilla-l10n/langchecker/pull/873/files#diff-913ec76ed4663fa42b51ed974ca60902R438 need a `,` after the last locale, so it should be `'fr',`

**Comment by alexgibson** [comment]
@peiying2 updated, thank you.

**Comment by peiying2** [comment]
Looks good. @flodolo please merge the PR.

**Pull request merged**
